import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { randomBytes } from "node:crypto";

const prisma = new PrismaClient();

// Unsplash photo IDs for high-quality furniture/interior shots.
// URL format: https://images.unsplash.com/photo-{ID}?w=600&h=400&fit=crop&auto=format&q=80
function unsplash(id: string) {
  return `https://images.unsplash.com/photo-${id}?w=600&h=400&fit=crop&auto=format&q=80`;
}

const products = [
  // ── Sofas ────────────────────────────────────────────────────────────────────
  {
    retailer: "john_lewis",
    externalId: "JL-SOFA-001",
    title: "John Lewis Camber Large 3 Seater Sofa",
    imageUrl: unsplash("1555041469-a586c61ea9bc"),
    productUrl: "https://www.johnlewis.com/john-lewis-camber-large-3-seater-sofa/p3809175",
    affiliateUrl: null,
    widthMm: 2200, depthMm: 1000, heightMm: 870,
    dimensionsRaw: "W220 × D100 × H87 cm",
    priceGbp: 1199,
    category: "sofa",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-SOFA-001",
    title: "Elara Corner Sofa, Modern Grey Fabric",
    imageUrl: unsplash("1493663284031-b7e3aefcae8e"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/corner-sofas-c1866678.html",
    affiliateUrl: null,
    widthMm: 2800, depthMm: 1600, heightMm: 860,
    dimensionsRaw: "W280 × D160 × H86 cm",
    priceGbp: 649,
    category: "sofa",
    styleTags: JSON.stringify(["contemporary_luxe"]),
  },
  {
    retailer: "dunelm",
    externalId: "DUN-SOFA-001",
    title: "Dunelm Darwin 3 Seater Sofa, Charcoal Fabric",
    imageUrl: unsplash("1484101851962-3e59c52f6bc7"),
    productUrl: "https://www.dunelm.com/product/darwin-3-seater-sofa-1000251172",
    affiliateUrl: null,
    widthMm: 2100, depthMm: 950, heightMm: 820,
    dimensionsRaw: "W210 × D95 × H82 cm",
    priceGbp: 599,
    category: "sofa",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-SOFA-001",
    title: "Habitat Jacob Velvet 3 Seater Sofa, Orange",
    imageUrl: unsplash("1583847268-347f75c2b06a"),
    productUrl: "https://www.habitat.co.uk/product/2910246",
    affiliateUrl: null,
    widthMm: 1800, depthMm: 850, heightMm: 790,
    dimensionsRaw: "W180 × D85 × H79 cm",
    priceGbp: 750,
    category: "sofa",
    styleTags: JSON.stringify(["mid_century", "bohemian"]),
  },
  {
    retailer: "john_lewis",
    externalId: "JL-SOFA-002",
    title: "John Lewis Nest Large 3 Seater Sofa",
    imageUrl: unsplash("1540518614846-7eded433c457"),
    productUrl: "https://www.johnlewis.com/john-lewis-nest-large-3-seater-sofa/p111325877",
    affiliateUrl: null,
    widthMm: 1900, depthMm: 970, heightMm: 840,
    dimensionsRaw: "W190 × D97 × H84 cm",
    priceGbp: 1399,
    category: "sofa",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },

  // ── Armchairs ────────────────────────────────────────────────────────────────
  {
    retailer: "la_redoute",
    externalId: "LR-CHAIR-001",
    title: "La Redoute So'Home Mid-Century Bouclé Armchair",
    imageUrl: unsplash("1558618666-fcd25c85cd64"),
    productUrl: "https://www.laredoute.co.uk/ppdp/prod-350374770.aspx",
    affiliateUrl: null,
    widthMm: 780, depthMm: 800, heightMm: 900,
    dimensionsRaw: "W78 × D80 × H90 cm",
    priceGbp: 349,
    category: "armchair",
    styleTags: JSON.stringify(["mid_century", "scandi"]),
  },
  {
    retailer: "john_lewis",
    externalId: "JL-CHAIR-001",
    title: "John Lewis Huxley Leather Armchair, Cognac Tan",
    imageUrl: unsplash("1567538096630-e0c55bd6374c"),
    productUrl: "https://www.johnlewis.com/furniture-lights/sofas/armchair",
    affiliateUrl: null,
    widthMm: 850, depthMm: 850, heightMm: 870,
    dimensionsRaw: "W85 × D85 × H87 cm",
    priceGbp: 699,
    category: "armchair",
    styleTags: JSON.stringify(["mid_century", "traditional"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-CHAIR-001",
    title: "Nora Swivel Chair, Cream Boucle",
    imageUrl: unsplash("1506439773649-6e0eb8cfb237"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/armchairs-c1866685.html",
    affiliateUrl: null,
    widthMm: 760, depthMm: 760, heightMm: 870,
    dimensionsRaw: "W76 × D76 × H87 cm",
    priceGbp: 349,
    category: "armchair",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-CHAIR-001",
    title: "Habitat 60 Scoop Fabric Chair, Green",
    imageUrl: unsplash("1519682577872-89ae92da0ea0"),
    productUrl: "https://www.habitat.co.uk/product/4728508",
    affiliateUrl: null,
    widthMm: 840, depthMm: 900, heightMm: 1050,
    dimensionsRaw: "W84 × D90 × H105 cm",
    priceGbp: 299,
    category: "armchair",
    styleTags: JSON.stringify(["mid_century", "scandi"]),
  },

  // ── Coffee Tables ─────────────────────────────────────────────────────────────
  {
    retailer: "habitat",
    externalId: "HAB-CT-001",
    title: "Habitat Akira Round Coffee Table, Solid Oak",
    imageUrl: unsplash("1549187774-b4e9b0445b41"),
    productUrl: "https://www.habitat.co.uk/browse/furniture/coffee-tables/c:809256/",
    affiliateUrl: null,
    widthMm: 800, depthMm: 800, heightMm: 420,
    dimensionsRaw: "Ø80 × H42 cm",
    priceGbp: 299,
    category: "coffee_table",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },
  {
    retailer: "dunelm",
    externalId: "DUN-CT-001",
    title: "Dunelm Amari Round Coffee Table, Oak",
    imageUrl: unsplash("1574269909626-97b91da23d6e"),
    productUrl: "https://www.dunelm.com/product/amari-round-coffee-table-1000242645",
    affiliateUrl: null,
    widthMm: 800, depthMm: 800, heightMm: 420,
    dimensionsRaw: "Ø80 × H42 cm",
    priceGbp: 129,
    category: "coffee_table",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-CT-001",
    title: "Dexter Industrial Coffee Table, Reclaimed Wood & Steel",
    imageUrl: unsplash("1493815780673-f79d8bd2e60f"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/coffee-tables-c1866684.html",
    affiliateUrl: null,
    widthMm: 1200, depthMm: 650, heightMm: 430,
    dimensionsRaw: "W120 × D65 × H43 cm",
    priceGbp: 249,
    category: "coffee_table",
    styleTags: JSON.stringify(["industrial"]),
  },
  {
    retailer: "john_lewis",
    externalId: "JL-CT-001",
    title: "John Lewis Estate Coffee Table, Natural",
    imageUrl: unsplash("1524758631624-e2822f1d959a"),
    productUrl: "https://www.johnlewis.com/john-lewis-estate-coffee-table-natural/p3743328",
    affiliateUrl: null,
    widthMm: 1100, depthMm: 600, heightMm: 430,
    dimensionsRaw: "W110 × D60 × H43 cm",
    priceGbp: 349,
    category: "coffee_table",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },

  // ── Dining Tables ─────────────────────────────────────────────────────────────
  {
    retailer: "john_lewis",
    externalId: "JL-DT-001",
    title: "John Lewis Anton 6-8 Seater Extending Dining Table, Oak",
    imageUrl: unsplash("1556909114-f6e7ad7d3136"),
    productUrl: "https://www.johnlewis.com/john-lewis-anton-6-8-seater-extending-dining-table-oak/p6293478",
    affiliateUrl: null,
    widthMm: 1600, depthMm: 800, heightMm: 760,
    dimensionsRaw: "W160–220 × D80 × H76 cm (extends to 220 cm)",
    priceGbp: 999,
    category: "dining_table",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-DT-001",
    title: "Marcus Dining Table, Black Steel & Walnut, 6 Seat",
    imageUrl: unsplash("1568092435578-306a1feadedf"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/dining-tables-c1866690.html",
    affiliateUrl: null,
    widthMm: 1800, depthMm: 900, heightMm: 760,
    dimensionsRaw: "W180 × D90 × H76 cm",
    priceGbp: 499,
    category: "dining_table",
    styleTags: JSON.stringify(["industrial"]),
  },
  {
    retailer: "dunelm",
    externalId: "DUN-DT-001",
    title: "Dunelm Kobe Compact Rectangular Dining Table with 4 Chairs",
    imageUrl: unsplash("1594540579-47b1fc97e29f"),
    productUrl: "https://www.dunelm.com/product/kobe-compact-rectangular-dining-table-with-4-chairs-1000207004",
    affiliateUrl: null,
    widthMm: 1200, depthMm: 750, heightMm: 760,
    dimensionsRaw: "W120 × D75 × H76 cm",
    priceGbp: 399,
    category: "dining_table",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-DT-001",
    title: "Habitat Bruno Solid Beech Dining Table, 4 Seat",
    imageUrl: unsplash("1560185007-5f0bb1cf4b0e"),
    productUrl: "https://www.habitat.co.uk/browse/furniture/dining-tables/c:809243/",
    affiliateUrl: null,
    widthMm: 1500, depthMm: 800, heightMm: 740,
    dimensionsRaw: "W150 × D80 × H74 cm",
    priceGbp: 849,
    category: "dining_table",
    styleTags: JSON.stringify(["mid_century", "scandi"]),
  },

  // ── Beds ─────────────────────────────────────────────────────────────────────
  {
    retailer: "john_lewis",
    externalId: "JL-BED-001",
    title: "John Lewis Bow Platform Bed Frame, Double, Oak/Natural",
    imageUrl: unsplash("1555529669-e69e7aa0ba9a"),
    productUrl: "https://www.johnlewis.com/john-lewis-bow-platform-bed-frame-double-oak-natural/p4013553",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2200, heightMm: 900,
    dimensionsRaw: "W155 × D220 × H90 cm (Double)",
    priceGbp: 699,
    category: "bed",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "la_redoute",
    externalId: "LR-BED-001",
    title: "La Redoute Jimi Solid Pine Platform Bed, Oak-Stained",
    imageUrl: unsplash("1586717791821-3cfad1341012"),
    productUrl: "https://www.laredoute.co.uk/ppdp/prod-324481772.aspx",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2100, heightMm: 300,
    dimensionsRaw: "W155 × D210 × H30 cm (Double)",
    priceGbp: 299,
    category: "bed",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-BED-001",
    title: "Luna Rattan Bed Frame, King, Natural",
    imageUrl: unsplash("1522771739844-12a943e5af79"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/bed-frames-c1866693.html",
    affiliateUrl: null,
    widthMm: 1870, depthMm: 2270, heightMm: 1200,
    dimensionsRaw: "W187 × D227 × H120 cm (King)",
    priceGbp: 549,
    category: "bed",
    styleTags: JSON.stringify(["bohemian"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-BED-001",
    title: "Habitat Loft Metal Bed Frame, Double, Matte Black",
    imageUrl: unsplash("1540638349517-3abd5afc5847"),
    productUrl: "https://www.habitat.co.uk/browse/furniture/beds-and-bed-frames/c:809265/",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2200, heightMm: 1100,
    dimensionsRaw: "W155 × D220 × H110 cm (Double)",
    priceGbp: 449,
    category: "bed",
    styleTags: JSON.stringify(["industrial"]),
  },
  {
    retailer: "john_lewis",
    externalId: "JL-BED-002",
    title: "John Lewis Edwin Bed Frame, Double, Stained Oak",
    imageUrl: unsplash("1588046130571-de4d2ae78a11"),
    productUrl: "https://www.johnlewis.com/john-lewis-edwin-bed-frame-double-stained-oak/p111239826",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2200, heightMm: 1050,
    dimensionsRaw: "W155 × D220 × H105 cm (Double)",
    priceGbp: 699,
    category: "bed",
    styleTags: JSON.stringify(["mid_century", "traditional"]),
  },

  // ── Amazon ────────────────────────────────────────────────────────────────────
  {
    retailer: "amazon",
    externalId: "AMZ-SOFA-001",
    title: "Home Detail Velvet 3 Seater Sofa, Black",
    imageUrl: unsplash("1555041469-a586c61ea9bc"),
    productUrl: "https://www.amazon.co.uk/Velvet-Fabric-Seater-Upholstered-Furniture/dp/B095TKQHSW",
    affiliateUrl: null,
    widthMm: 1850, depthMm: 770, heightMm: 700,
    dimensionsRaw: "W185 × D77 × H70 cm",
    priceGbp: 189,
    category: "sofa",
    styleTags: JSON.stringify(["contemporary_luxe", "industrial"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-SOFA-002",
    title: "Luxury Life Elegance Grey Chenille 3 Seater Sofa",
    imageUrl: unsplash("1493663284031-b7e3aefcae8e"),
    productUrl: "https://www.amazon.co.uk/Elegance-Grey-Sofa-Velvet-Chenille/dp/B094DD68MX",
    affiliateUrl: null,
    widthMm: 2050, depthMm: 900, heightMm: 780,
    dimensionsRaw: "W205 × D90 × H78 cm",
    priceGbp: 249,
    category: "sofa",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-CHAIR-001",
    title: "HOMCOM Boucle Accent Armchair, Grey",
    imageUrl: unsplash("1558618666-fcd25c85cd64"),
    productUrl: "https://www.amazon.co.uk/HOMCOM-Armchair-Occasional-Bedroom-Reception/dp/B0DHL12TYT",
    affiliateUrl: null,
    widthMm: 705, depthMm: 650, heightMm: 730,
    dimensionsRaw: "W70.5 × D65 × H73 cm",
    priceGbp: 149,
    category: "armchair",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-CT-001",
    title: "Hallowood Waverly Solid Oak Coffee Table with Shelf",
    imageUrl: unsplash("1549187774-b4e9b0445b41"),
    productUrl: "https://www.amazon.co.uk/Hallowood-Waverly-Coffee-Rectangular-Storage/dp/B01LWVEZ1C",
    affiliateUrl: null,
    widthMm: 900, depthMm: 450, heightMm: 450,
    dimensionsRaw: "W90 × D45 × H45 cm",
    priceGbp: 139,
    category: "coffee_table",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-DT-001",
    title: "Vida Designs Medina 4 Seater Dining Table, Oak",
    imageUrl: unsplash("1556909114-f6e7ad7d3136"),
    productUrl: "https://www.amazon.co.uk/Vida-Designs-Rectangle-Kitchen-Furniture/dp/B07NMMSMVK",
    affiliateUrl: null,
    widthMm: 1200, depthMm: 800, heightMm: 760,
    dimensionsRaw: "W120 × D80 × H76 cm",
    priceGbp: 129,
    category: "dining_table",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-BED-001",
    title: "Bespoke Beds Upholstered Ottoman Storage Bed, Double, Sand",
    imageUrl: unsplash("1555529669-e69e7aa0ba9a"),
    productUrl: "https://www.amazon.co.uk/BESPOKE-BEDS-Upholstered-Ottoman-Storage/dp/B0D2X1S2TK",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2200, heightMm: 1100,
    dimensionsRaw: "W155 × D220 × H110 cm (Double)",
    priceGbp: 349,
    category: "bed",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },
  {
    retailer: "amazon",
    externalId: "AMZ-LIGHT-001",
    title: "HOMCOM 3-Tier Floor Lamp with Storage Shelves, Oak",
    imageUrl: unsplash("1507473885765-e6ed057f782c"),
    productUrl: "https://www.amazon.co.uk/HOMCOM-Storage-Reading-Standing-Bedroom/dp/B08LXWP98G",
    affiliateUrl: null,
    widthMm: 400, depthMm: 400, heightMm: 1600,
    dimensionsRaw: "W40 × D40 × H160 cm",
    priceGbp: 65,
    category: "lighting",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },

  // ── Muji ──────────────────────────────────────────────────────────────────────
  {
    retailer: "muji",
    externalId: "MUJI-SOFA-001",
    title: "Muji Modular Sofa Unit, Dark Grey, 2-Seat",
    imageUrl: unsplash("1555041469-a586c61ea9bc"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/sofas/",
    affiliateUrl: null,
    widthMm: 1700, depthMm: 880, heightMm: 740,
    dimensionsRaw: "W170 × D88 × H74 cm",
    priceGbp: 699,
    category: "sofa",
    styleTags: JSON.stringify(["scandi", "japandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-CHAIR-001",
    title: "Muji Reclining High Back Chair, Natural Beech",
    imageUrl: unsplash("1506439773649-6e0eb8cfb237"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/chairs/",
    affiliateUrl: null,
    widthMm: 660, depthMm: 700, heightMm: 1020,
    dimensionsRaw: "W66 × D70 × H102 cm",
    priceGbp: 349,
    category: "armchair",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-CT-001",
    title: "Muji Oak Coffee Table, 120×60 cm",
    imageUrl: unsplash("1524758631624-e2822f1d959a"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/tables/",
    affiliateUrl: null,
    widthMm: 1200, depthMm: 600, heightMm: 380,
    dimensionsRaw: "W120 × D60 × H38 cm",
    priceGbp: 195,
    category: "coffee_table",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-DT-001",
    title: "Muji Oak Dining Table, 140×80 cm, 4–6 Seat",
    imageUrl: unsplash("1556909114-f6e7ad7d3136"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/dining/",
    affiliateUrl: null,
    widthMm: 1400, depthMm: 800, heightMm: 720,
    dimensionsRaw: "W140 × D80 × H72 cm",
    priceGbp: 395,
    category: "dining_table",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-BED-001",
    title: "Muji Beech Bed Frame, Double, Slatted",
    imageUrl: unsplash("1555529669-e69e7aa0ba9a"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/beds/",
    affiliateUrl: null,
    widthMm: 1550, depthMm: 2100, heightMm: 250,
    dimensionsRaw: "W155 × D210 × H25 cm (Double)",
    priceGbp: 449,
    category: "bed",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-STO-001",
    title: "Muji Stacking Shelf, Oak, 3 Tiers",
    imageUrl: unsplash("1565538708542-56a4c5c9d714"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/shelves/",
    affiliateUrl: null,
    widthMm: 840, depthMm: 285, heightMm: 1215,
    dimensionsRaw: "W84 × D28.5 × H121.5 cm",
    priceGbp: 249,
    category: "storage",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-STO-002",
    title: "Muji Polypropylene Storage Unit, 3 Drawers, Wide",
    imageUrl: unsplash("1543163521-1bf539c55dd2"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/storage/",
    affiliateUrl: null,
    widthMm: 390, depthMm: 550, heightMm: 540,
    dimensionsRaw: "W39 × D55 × H54 cm",
    priceGbp: 79,
    category: "storage",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },

  // ── Storage ───────────────────────────────────────────────────────────────────
  {
    retailer: "habitat",
    externalId: "HAB-STO-001",
    title: "Habitat Nori Bookcase, Solid Oak, 4 Shelves",
    imageUrl: unsplash("1565538708542-56a4c5c9d714"),
    productUrl: "https://www.habitat.co.uk/browse/furniture/bookcases-and-shelving/c:809250/",
    affiliateUrl: null,
    widthMm: 800, depthMm: 350, heightMm: 1800,
    dimensionsRaw: "W80 × D35 × H180 cm",
    priceGbp: 349,
    category: "storage",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },
  {
    retailer: "dunelm",
    externalId: "DUN-STO-001",
    title: "Dunelm Sideboard, Oak & Brass Finish",
    imageUrl: unsplash("1543163521-1bf539c55dd2"),
    productUrl: "https://www.dunelm.com/category/home-and-furniture/furniture/living-room-furniture/sideboards-and-buffets",
    affiliateUrl: null,
    widthMm: 1500, depthMm: 450, heightMm: 800,
    dimensionsRaw: "W150 × D45 × H80 cm",
    priceGbp: 299,
    category: "storage",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-STO-001",
    title: "Byron Industrial Shelving Unit, Black Metal & Pine",
    imageUrl: unsplash("1518455027859-f3b9c2c5b2a8"),
    productUrl: "https://www.wayfair.co.uk/furniture/sb1/bookcases-c1866692.html",
    affiliateUrl: null,
    widthMm: 900, depthMm: 350, heightMm: 1800,
    dimensionsRaw: "W90 × D35 × H180 cm",
    priceGbp: 199,
    category: "storage",
    styleTags: JSON.stringify(["industrial"]),
  },
  {
    retailer: "john_lewis",
    externalId: "JL-STO-001",
    title: "John Lewis Elda TV & Media Unit, White & Light Oak",
    imageUrl: unsplash("1563298289-eb28efa0dfc7"),
    productUrl: "https://www.johnlewis.com/browse/furniture-lights/living-room/tv-entertainment/_/N-c4z",
    affiliateUrl: null,
    widthMm: 1600, depthMm: 400, heightMm: 550,
    dimensionsRaw: "W160 × D40 × H55 cm",
    priceGbp: 449,
    category: "storage",
    styleTags: JSON.stringify(["scandi", "contemporary_luxe"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-STO-002",
    title: "Habitat Jute Storage Basket Set of 3, Natural",
    imageUrl: unsplash("1544967082-786169707f8f"),
    productUrl: "https://www.habitat.co.uk/browse/furniture/storage/c:809248/",
    affiliateUrl: null,
    widthMm: 400, depthMm: 400, heightMm: 350,
    dimensionsRaw: "Small/Medium/Large (sold as set)",
    priceGbp: 79,
    category: "storage",
    styleTags: JSON.stringify(["bohemian", "scandi"]),
  },
  {
    retailer: "la_redoute",
    externalId: "LR-STO-001",
    title: "La Redoute 2-Door Wardrobe, Natural Wood",
    imageUrl: unsplash("1586023492125-27b2c045efd3"),
    productUrl: "https://www.laredoute.co.uk/pplp/100/75363/cat-75409.aspx",
    affiliateUrl: null,
    widthMm: 1200, depthMm: 580, heightMm: 2100,
    dimensionsRaw: "W120 × D58 × H210 cm",
    priceGbp: 495,
    category: "storage",
    styleTags: JSON.stringify(["scandi", "mid_century"]),
  },

  // ── Lighting ──────────────────────────────────────────────────────────────────
  {
    retailer: "john_lewis",
    externalId: "JL-LIGHT-001",
    title: "John Lewis Hector Floor Lamp",
    imageUrl: unsplash("1507473885765-e6ed057f782c"),
    productUrl: "https://www.johnlewis.com/john-lewis-hector-floor-lamp/p3689364",
    affiliateUrl: null,
    widthMm: 320, depthMm: 320, heightMm: 1620,
    dimensionsRaw: "Ø32 × H162 cm",
    priceGbp: 249,
    category: "lighting",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi", "mid_century"]),
  },
  {
    retailer: "habitat",
    externalId: "HAB-LIGHT-001",
    title: "Habitat Arched Floor Lamp, Matte Black",
    imageUrl: unsplash("1513506003901-1e6a35d44a4a"),
    productUrl: "https://www.habitat.co.uk/browse/lighting/floor-and-standard-lamps/c:809328/",
    affiliateUrl: null,
    widthMm: 350, depthMm: 350, heightMm: 1800,
    dimensionsRaw: "Ø35 × H180 cm",
    priceGbp: 89,
    category: "lighting",
    styleTags: JSON.stringify(["industrial", "scandi", "contemporary_luxe"]),
  },
  {
    retailer: "wayfair",
    externalId: "WF-LIGHT-001",
    title: "Boho Rattan Pendant Light, Natural, Large",
    imageUrl: unsplash("1524484485831-a92ffc0de03f"),
    productUrl: "https://www.wayfair.co.uk/lighting/sb1/pendant-lights-c1866699.html",
    affiliateUrl: null,
    widthMm: 500, depthMm: 500, heightMm: 400,
    dimensionsRaw: "Ø50 × H40 cm (shade only)",
    priceGbp: 69,
    category: "lighting",
    styleTags: JSON.stringify(["bohemian", "coastal", "scandi"]),
  },
  {
    retailer: "dunelm",
    externalId: "DUN-LIGHT-001",
    title: "Dunelm Voss 2-Light Floor Lamp",
    imageUrl: unsplash("1558618047-3f10fb96c1b5"),
    productUrl: "https://www.dunelm.com/product/voss-floor-lamp-1000196019",
    affiliateUrl: null,
    widthMm: 300, depthMm: 300, heightMm: 1500,
    dimensionsRaw: "Ø30 × H150 cm",
    priceGbp: 59,
    category: "lighting",
    styleTags: JSON.stringify(["contemporary_luxe", "scandi"]),
  },
  {
    retailer: "la_redoute",
    externalId: "LR-LIGHT-001",
    title: "La Redoute Interieurs Ceramic & Brass Table Lamp",
    imageUrl: unsplash("1524484485831-a92ffc0de03f"),
    productUrl: "https://www.laredoute.co.uk/pplp/cat-385401.aspx",
    affiliateUrl: null,
    widthMm: 200, depthMm: 200, heightMm: 580,
    dimensionsRaw: "Ø20 × H58 cm",
    priceGbp: 95,
    category: "lighting",
    styleTags: JSON.stringify(["contemporary_luxe", "mid_century"]),
  },
  {
    retailer: "muji",
    externalId: "MUJI-LIGHT-001",
    title: "Muji LED Portable Lamp, Warm White",
    imageUrl: unsplash("1513506003901-1e6a35d44a4a"),
    productUrl: "https://www.muji.com/uk/products/clothing_shoes/lighting/",
    affiliateUrl: null,
    widthMm: 120, depthMm: 120, heightMm: 290,
    dimensionsRaw: "Ø12 × H29 cm",
    priceGbp: 55,
    category: "lighting",
    styleTags: JSON.stringify(["japandi", "scandi"]),
  },
];

async function main() {
  // ── Admin user ───────────────────────────────────────────────────────────────
  // Reads from env so no real email/password is hardcoded in source. Falls back
  // to a generic local-dev address; the password is freshly randomised on every
  // run and printed once — never persisted anywhere but the hash in the DB.
  const adminEmail = process.env.ADMIN_EMAIL ?? "admin@example.com";
  const existingAdmin = await prisma.user.findUnique({ where: { email: adminEmail } });
  if (existingAdmin) {
    await prisma.user.update({ where: { email: adminEmail }, data: { isAdmin: true } });
    console.log(`Admin flag set on existing account: ${adminEmail}`);
  } else {
    const generatedPassword = randomBytes(9).toString("base64url"); // 12 chars, URL-safe
    const passwordHash = await bcrypt.hash(generatedPassword, 10);
    await prisma.user.create({
      data: { email: adminEmail, passwordHash, isAdmin: true },
    });
    console.log(`Admin account created: ${adminEmail} (password: ${generatedPassword} — save this, it won't be shown again)`);
  }

  // ── Provider cost entries — seed canonical list for current month ─────────────
  // Idempotent: removes any existing entry for known providers in this month,
  // then re-creates the definitive list. Manually entered costs (R2, Gemini)
  // should be updated each month via the admin UI.
  const SEED_MONTH = 5;
  const SEED_YEAR  = 2026;

  const canonicalProviders = [
    { provider: "Railway",            plan: "Backend hosting",  monthlyCostGbp: 18.50, status: "active",   notes: null },
    { provider: "Vercel",             plan: "Frontend hosting", monthlyCostGbp:  0.00, status: "active",   notes: "Free tier" },
    { provider: "Cloudflare R2",      plan: "File storage",     monthlyCostGbp:  0.00, status: "active",   notes: "Manual entry — pay per use" },
    { provider: "Gemini API",         plan: "AI generation",    monthlyCostGbp:  0.00, status: "active",   notes: "Manual entry — pay per use" },
    { provider: "OpenAI API",         plan: "Not used",         monthlyCostGbp:  0.00, status: "inactive", notes: "Not active — kept as future option" },
    { provider: "Resend",             plan: "Email service",    monthlyCostGbp:  0.00, status: "active",   notes: "Free tier" },
    { provider: "Awin",               plan: "Affiliate network",monthlyCostGbp:  6.00, status: "pending",  notes: "Pending approval" },
    { provider: "Amazon Associates",  plan: "Affiliate",        monthlyCostGbp:  0.00, status: "active",   notes: "Commission only — no monthly fee" },
    { provider: "Domain (.co.uk)",    plan: "Annual plan",      monthlyCostGbp:  1.25, status: "active",   notes: "myinteriordesigner.co.uk — £15/yr ÷ 12" },
  ];

  await prisma.costEntry.deleteMany({
    where: {
      month: SEED_MONTH, year: SEED_YEAR,
      provider: { in: canonicalProviders.map(p => p.provider) },
    },
  });

  await prisma.costEntry.createMany({
    data: canonicalProviders.map(p => ({ ...p, month: SEED_MONTH, year: SEED_YEAR })),
  });

  console.log(`Seeded ${canonicalProviders.length} provider cost entries for ${SEED_MONTH}/${SEED_YEAR}`);

  // ── Products ─────────────────────────────────────────────────────────────────
  await prisma.product.deleteMany({});

  for (const p of products) {
    await prisma.product.upsert({
      where: { retailer_externalId: { retailer: p.retailer, externalId: p.externalId } },
      create: p,
      update: p,
    });
  }

  console.log(`Seeded ${products.length} products`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
