import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — My Interior Designer",
  description: "Terms and conditions for using My Interior Designer.",
};

const UPDATED = "26 May 2026";

function H2({ id, children }: { id: string; children: React.ReactNode }) {
  return (
    <h2 id={id} className="text-xl font-bold text-stone-900 mt-12 mb-4 scroll-mt-24">
      {children}
    </h2>
  );
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-stone-600 leading-relaxed mb-3">{children}</p>;
}
function UL({ children }: { children: React.ReactNode }) {
  return <ul className="list-disc pl-6 space-y-1.5 text-stone-600 mb-4">{children}</ul>;
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="border-b border-stone-200 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-sm text-stone-500 hover:text-stone-900 transition-colors">
            ← Back to My Interior Designer
          </Link>
          <span className="text-xs text-stone-400">Last updated: {UPDATED}</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-stone-900 mb-2">Terms of Service</h1>
        <p className="text-stone-500 mb-8">Last updated: {UPDATED}</p>

        <P>
          Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully before using My
          Interior Designer (&ldquo;the Service&rdquo;) operated by My Interior Designer
          (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) at myinteriordesigner.co.uk.
          By creating an account or using the Service, you agree to these Terms. If you do not
          agree, do not use the Service.
        </P>

        <H2 id="service">1. Description of Service</H2>
        <P>
          My Interior Designer is an AI-powered interior design tool that allows you to upload
          floor plan images, specify room preferences and furniture, and receive AI-generated
          room render images. We also provide product browsing features with links to third-party
          furniture retailers.
        </P>
        <P>
          The Service is intended for personal, non-commercial use unless otherwise agreed in
          writing with us.
        </P>

        <H2 id="eligibility">2. Eligibility</H2>
        <P>
          You must be at least 13 years old to use the Service. By creating an account you
          confirm that you meet this requirement. If you are under 18, you should have parental
          or guardian consent before using the Service.
        </P>

        <H2 id="account">3. Your Account</H2>
        <P>
          You are responsible for maintaining the confidentiality of your account credentials
          and for all activity that occurs under your account. You must:
        </P>
        <UL>
          <li>Provide accurate information when registering</li>
          <li>Keep your password secure and not share it with others</li>
          <li>Notify us immediately at <a href="mailto:hello@myinteriordesigner.co.uk" className="underline">hello@myinteriordesigner.co.uk</a> if you suspect unauthorised access</li>
        </UL>
        <P>
          We reserve the right to suspend or terminate accounts that breach these Terms.
        </P>

        <H2 id="acceptable-use">4. Acceptable Use</H2>
        <P>You agree not to use the Service to:</P>
        <UL>
          <li>Upload content that is illegal, harmful, offensive, or infringes third-party rights</li>
          <li>Upload floor plans or images that contain personal data of others without their consent</li>
          <li>Attempt to reverse-engineer, scrape, or extract data from the Service</li>
          <li>Use automated tools to make requests to the Service beyond normal use</li>
          <li>Resell, sublicense, or commercially exploit the Service without our written permission</li>
          <li>Attempt to circumvent usage limits or security measures</li>
          <li>Use the Service for any unlawful purpose or in violation of any applicable law</li>
        </UL>

        <H2 id="ai-content">5. AI-Generated Content</H2>
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-4">
          <p className="text-amber-900 font-semibold text-sm mb-2">Important — please read carefully</p>
          <p className="text-amber-800 text-sm leading-relaxed">
            The room renders generated by this Service are <strong>created by artificial intelligence</strong> and
            are provided for inspiration and visualisation purposes only. They are <strong>not professional
            interior design advice</strong>, architectural drawings, or structural recommendations.
          </p>
        </div>
        <P>
          AI-generated renders may contain inaccuracies, impossible layouts, or furniture that
          does not match exact product dimensions. Always verify furniture dimensions against your
          actual room measurements before purchasing. We accept no liability for purchasing
          decisions made based on AI-generated renders.
        </P>
        <P>
          We use Google Gemini to generate renders. Output quality and style may vary. We do not
          guarantee any particular aesthetic result. You can regenerate renders at any time within
          your monthly allowance.
        </P>

        <H2 id="ip">6. Intellectual Property</H2>
        <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">Your content</h3>
        <P>
          You retain full ownership of all content you upload to the Service, including floor
          plan images and any other materials. You also own the AI-generated render images
          produced from your inputs. By uploading content, you grant us a limited licence to
          store and process it solely for the purpose of providing the Service to you.
        </P>
        <P>
          You may download, use, share, and publish your render images for personal or
          commercial purposes. If you share renders publicly, we appreciate (but do not require)
          a credit to My Interior Designer.
        </P>
        <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">Our content</h3>
        <P>
          The My Interior Designer name, logo, website design, software, and all content we
          produce remain our exclusive property. Nothing in these Terms grants you any right to
          use our brand, trademarks, or proprietary technology.
        </P>

        <H2 id="third-party">7. Third-Party Links</H2>
        <P>
          The Service displays links to furniture products on third-party retailer websites. We
          may earn affiliate commission on purchases made through these links. We are not
          responsible for the content, accuracy, availability, pricing, or terms of third-party
          websites. Your use of those websites is governed by their own terms and policies.
        </P>

        <H2 id="liability">8. Limitation of Liability</H2>
        <P>
          To the fullest extent permitted by English law, we exclude all liability for:
        </P>
        <UL>
          <li>Loss of data or damage to systems resulting from use of the Service</li>
          <li>Purchasing decisions made based on AI-generated renders</li>
          <li>Temporary unavailability of the Service</li>
          <li>Any indirect, consequential, or incidental losses</li>
        </UL>
        <P>
          Nothing in these Terms excludes or limits our liability for death or personal injury
          caused by our negligence, fraud, or any other liability that cannot be excluded by law.
        </P>
        <P>
          The Service is provided &ldquo;as is&rdquo; without warranty of any kind. We do not
          warrant that the Service will be uninterrupted, error-free, or that AI renders will
          meet your specific requirements.
        </P>

        <H2 id="availability">9. Service Availability</H2>
        <P>
          We aim to keep the Service available but do not guarantee 100% uptime. We may
          occasionally take the Service offline for maintenance, updates, or due to circumstances
          beyond our control. We will endeavour to provide notice of planned downtime where
          possible.
        </P>
        <P>
          We reserve the right to modify, suspend, or discontinue the Service at any time. If we
          discontinue the Service permanently, we will give you reasonable notice and the
          opportunity to download your data.
        </P>

        <H2 id="termination">10. Termination</H2>
        <P>
          You may close your account at any time via Account Settings → Privacy → Delete My
          Account. On deletion, all your data is permanently removed.
        </P>
        <P>
          We may suspend or terminate your account if you breach these Terms, engage in abusive
          behaviour, or for any other reason at our reasonable discretion. We will notify you by
          email where possible.
        </P>

        <H2 id="governing-law">11. Governing Law</H2>
        <P>
          These Terms are governed by and construed in accordance with the laws of{" "}
          <strong>England and Wales</strong>. Any dispute arising from these Terms or your use
          of the Service will be subject to the exclusive jurisdiction of the courts of England
          and Wales.
        </P>

        <H2 id="changes">12. Changes to These Terms</H2>
        <P>
          We may update these Terms from time to time. We will notify you of material changes by
          email and update the &ldquo;last updated&rdquo; date above. Continued use of the Service
          after notification constitutes acceptance of the revised Terms.
        </P>

        <H2 id="contact">13. Contact Us</H2>
        <P>
          For questions about these Terms, contact us at:{" "}
          <a href="mailto:hello@myinteriordesigner.co.uk" className="underline">
          hello@myinteriordesigner.co.uk</a>
        </P>

        <div className="border-t border-stone-200 pt-6 mt-12">
          <div className="flex flex-wrap gap-4 text-sm text-stone-500">
            <Link href="/privacy" className="hover:text-stone-900 underline transition-colors">Privacy Policy</Link>
            <a href="mailto:hello@myinteriordesigner.co.uk" className="hover:text-stone-900 underline transition-colors">Contact Us</a>
            <Link href="/" className="hover:text-stone-900 underline transition-colors">Back to My Interior Designer</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
